# Generated by Django 4.2.6 on 2023-10-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_address_line_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line',
        ),
    ]
